### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by ak1920** [AhsenChaudhry/Mitochondria-Analyzer#1]
Hi,
Firstly Thank you very much for this plugin, it works but gives me this exception.
I assume its partly due to opencv, I use Mac and could not use the the openCV.jar you kindly provide.
I would appreciate any suggestions,
Tekrar cok tesekkurler ve basarilar,

(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_202 [64-bit]; Mac OS X 10.15.6; 228MB of 8492MB (2%)
 
java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1043)
	at org.bytedeco.javacpp.Loader.load(Loader.java:935)
	at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:994)
	at org.bytedeco.javacpp.Loader.load(Loader.java:951)
	at adaptiveThr_.run(adaptiveThr_.java:162)
	at adaptiveThr_.showDialog(adaptiveThr_.java:112)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:63)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runUserPlugIn(IJ.java:250)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:65)
	at ij.IJ.run(IJ.java:317)
	at ij.IJ.run(IJ.java:328)
	at ij.macro.Functions.doRun(Functions.java:686)
	at ij.macro.Functions.doFunction(Functions.java:98)
	at ij.macro.Interpreter.doStatement(Interpreter.java:278)
	at ij.macro.Interpreter.doBlock(Interpreter.java:712)
	at ij.macro.Interpreter.doStatement(Interpreter.java:323)
	at ij.macro.Interpreter.doIf(Interpreter.java:1090)
	at ij.macro.Interpreter.doStatement(Interpreter.java:299)
	at ij.macro.Interpreter.doBlock(Interpreter.java:712)
	at ij.macro.Interpreter.runFirstMacro(Interpreter.java:813)
	at ij.macro.Interpreter.doStatement(Interpreter.java:314)
	at ij.macro.Interpreter.doStatements(Interpreter.java:264)
	at ij.macro.Interpreter.run(Interpreter.java:160)
	at ij.macro.Interpreter.run(Interpreter.java:93)
	at ij.macro.Interpreter.run(Interpreter.java:104)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:161)
	at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:145)
	at ij.IJ.runMacroFile(IJ.java:165)
	at ij.IJ.runMacroFile(IJ.java:170)
	at Mitochondria_Analyzer.lambda$run_Macro$0(Mitochondria_Analyzer.java:274)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1021)
	... 36 more

**Comment by razia0225** [comment]
Hello, 

I tried to follow the instructions for installation in method 1. However, the SigmaFilterplus file is not installed and I get the following error.

Macro Error

Unrecognized command: "Sigma FIlter Plus" in line 178. 

I tried to copy  the Sigma Filter Plus class file from the URL and paste in the plugins folder. But its giving me the same error.

Please advise.

Thanks.

**Comment by razia0225** [comment]
Here is the debug file


Memory	*	63MB of 6040MB (1%)
nImages()	*	2
getTitle()	*	"TMRM 7.3.2020_con 4Snapshot1.tif thresholded"
macroFolder	*	"C:\Users\rsmoham2\Desktop\FIJI-W~1\Fiji.app\plugins\MitochondriaAnalyzer\Macros\"
regularMode	*	1
batchMode	*	0
optimizeMode	*	0
preProcessOnly	*	0
input	*	"TMRM 7.3.2020_con 4Snapshot1.tif"
baseSize	*	1.2500
baseSubtract	*	10
canSubtract	*	1
rolling	*	0.0039
canSigma	*	1
canEnhance	*	1
slope	*	1.8000
canGamma	*	1
gamma	*	0.8000
canDespeckle	*	1
canRemove	*	1
showComparison	*	0
canAnalyze	*	0
adaptiveSize	*	0.0039
adaptiveSubtract	*	10
methodChoices	*	array[4]
method	*	"Weighted Mean"
labels	*	array[2]
defaults	*	array[2]
output	*	"TMRM 7.3.2020_con 4Snapshot1.tif thresholded"
width	*	1357
height	*	1357
channels	*	1
slices	*	1
frames	*	1
c	*	1
s	*	1
f	*	1
unit	*	"microns"
pixelWidth	*	321.9057
pixelHeight	*	321.9057
sRadius	*	0.0004

---		---
Error:		Unrecognized command: "Sigma Filter Plus" in line 178:
	
		if ( canSigma ) run ( "Sigma Filter Plus" , "radius=" + sRadius + " use=2.0 minimum=0.2 outlier stack" <)> ;

**Comment by AhsenChaudhry** [comment]
Hi Razia,
Thanks for reaching out regarding your issue. I am not sure why Sigma Filter Plus wasn't downloaded for you, but downloading straight from the URL update site may be not working due to the altered file name.

Would you be able to try downloading directly from the original source (https://imagej.nih.gov/ij/plugins/download/Sigma_Filter_Plus.class), and placing that file into the plugins folder?

Let me know if your error still persists!
