### ISSUE TITLE
Exception plugin Filter

### ISSUE THREAD

**Issue by julietteglb** [AhsenChaudhry/Mitochondria-Analyzer#10]
Hi, 
Thank you very much for this plugin, but i have a little problem, it gives me this exception.
I have tried at Mac and Windows and each times i have the same exception message. I have tried to change pixels in microns and reloaded the folders but i don't find any solution. ! Each time i start the process, i have this exeception message and obtain a white threshold image. 

 I would appreciate any suggestions.
Thank you, Juliette

(Fiji Is Just) ImageJ 2.9.0/1.53t; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 167MB of 6040MB (2%)
 
java.lang.NullPointerException
	at Sigma_Filter_Plus.run(Sigma_Filter_Plus.java:103)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:254)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:239)
	at ij.IJ.runPlugIn(IJ.java:203)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at ij.IJ.run(IJ.java:319)
	at ij.IJ.run(IJ.java:330)
	at ij.macro.Functions.doRun(Functions.java:703)
	at ij.macro.Functions.doFunction(Functions.java:99)
	at ij.macro.Interpreter.doStatement(Interpreter.java:281)
	at ij.macro.Interpreter.doIf(Interpreter.java:1116)
	at ij.macro.Interpreter.doStatement(Interpreter.java:302)
	at ij.macro.Interpreter.doBlock(Interpreter.java:715)
	at ij.macro.Interpreter.doStatement(Interpreter.java:326)
	at ij.macro.Interpreter.doIf(Interpreter.java:1116)
	at ij.macro.Interpreter.doStatement(Interpreter.java:302)
	at ij.macro.Interpreter.doBlock(Interpreter.java:715)
	at ij.macro.Interpreter.runFirstMacro(Interpreter.java:816)
	at ij.macro.Interpreter.doStatement(Interpreter.java:317)
	at ij.macro.Interpreter.doStatements(Interpreter.java:267)
	at ij.macro.Interpreter.run(Interpreter.java:163)
	at ij.macro.Interpreter.run(Interpreter.java:93)
	at ij.macro.Interpreter.run(Interpreter.java:107)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:162)
	at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:146)
	at ij.IJ.runMacroFile(IJ.java:170)
	at ij.IJ.runMacroFile(IJ.java:175)
	at Mitochondria_Analyzer.run_Macro(Mitochondria_Analyzer.java:277)
	at Mitochondria_Analyzer.Threshold2D(Mitochondria_Analyzer.java:213)
	at Mitochondria_Analyzer.run(Mitochondria_Analyzer.java:33)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runPlugIn(IJ.java:203)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)

**Comment by AhsenChaudhry** [comment]
Hello Juliette. Sorry that you have been encountering this error! I believe this issue also arises when the values for the pixel width, height, and depth are larger than 0.24 (micron). I have applied a fix to resolve this. Please also make sure these image pixel values match your raw microscopy acquisition data. 
Let me know if the error persists after updating the threshold commands.
