### ISSUE TITLE
Exception Error Message

### ISSUE THREAD

**Issue by jsova93** [AhsenChaudhry/Mitochondria-Analyzer#2]
Hello, 

When I try to do a 3D threshold, an "Exception" error message pops up. Do you have any suggestions for how to solve this issue? Thanks! 

Exception: 
(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_202 [64-bit]; Mac OS X 10.15.7; 615MB of 7822MB (7%)
 
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_core
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:994)
	at org.bytedeco.javacpp.Loader.load(Loader.java:951)
	at adaptiveThr_.run(adaptiveThr_.java:162)
	at adaptiveThr_.showDialog(adaptiveThr_.java:112)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:63)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runUserPlugIn(IJ.java:250)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at ij.IJ.run(IJ.java:317)
	at ij.IJ.run(IJ.java:328)
	at ij.macro.Functions.doRun(Functions.java:686)
	at ij.macro.Functions.doFunction(Functions.java:98)
	at ij.macro.Interpreter.doStatement(Interpreter.java:278)
	at ij.macro.Interpreter.doBlock(Interpreter.java:712)
	at ij.macro.Interpreter.doStatement(Interpreter.java:323)
	at ij.macro.Interpreter.doFor(Interpreter.java:634)
	at ij.macro.Interpreter.doStatement(Interpreter.java:305)
	at ij.macro.Interpreter.doBlock(Interpreter.java:712)
	at ij.macro.Interpreter.doStatement(Interpreter.java:323)
	at ij.macro.Interpreter.doIf(Interpreter.java:1090)
	at ij.macro.Interpreter.doStatement(Interpreter.java:299)
	at ij.macro.Interpreter.doBlock(Interpreter.java:712)
	at ij.macro.Interpreter.runFirstMacro(Interpreter.java:813)
	at ij.macro.Interpreter.doStatement(Interpreter.java:314)
	at ij.macro.Interpreter.doStatements(Interpreter.java:264)
	at ij.macro.Interpreter.run(Interpreter.java:160)
	at ij.macro.Interpreter.run(Interpreter.java:93)
	at ij.macro.Interpreter.run(Interpreter.java:104)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:161)
	at ij.IJ.runMacro(IJ.java:153)
	at ij.IJ.runMacro(IJ.java:142)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1148)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1144)
	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:1095)
	at net.imagej.legacy.IJ1Helper.runMacro(IJ1Helper.java:1144)
	at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:145)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by AhsenChaudhry** [comment]
Hello,

Unfortunately, at this time our plugin is not compatible with MacOS, which is why you are receiving this error.  It is currently only compatible with ImageJ/Fiji on Windows.
