### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by BD1997856** [AhsenChaudhry/Mitochondria-Analyzer#7]
Hi there, 

I am attempting to use the Mitchondria Analyzer plug in on my Mac and I attempted to follow method 1 and 2 for installation and both were unsuccessful. I am currently getting this error. I also tried to move the Sigma Filter Plus Class into the plugins folder after downloading it from the link mentioned in issue #1 exception and still had no luck. This is the exception message I am getting: 

java.lang.NullPointerException
	at Sigma_Filter_Plus.run(Sigma_Filter_Plus.java:103)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:254)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:245)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at ij.IJ.run(IJ.java:325)
	at ij.IJ.run(IJ.java:336)
	at ij.macro.Functions.doRun(Functions.java:703)
	at ij.macro.Functions.doFunction(Functions.java:99)
	at ij.macro.Interpreter.doStatement(Interpreter.java:281)
	at ij.macro.Interpreter.doIf(Interpreter.java:1116)
	at ij.macro.Interpreter.doStatement(Interpreter.java:302)
	at ij.macro.Interpreter.doBlock(Interpreter.java:715)
	at ij.macro.Interpreter.doStatement(Interpreter.java:326)
	at ij.macro.Interpreter.doIf(Interpreter.java:1116)
	at ij.macro.Interpreter.doStatement(Interpreter.java:302)
	at ij.macro.Interpreter.doBlock(Interpreter.java:715)
	at ij.macro.Interpreter.runFirstMacro(Interpreter.java:816)
	at ij.macro.Interpreter.doStatement(Interpreter.java:317)
	at ij.macro.Interpreter.doStatements(Interpreter.java:267)
	at ij.macro.Interpreter.run(Interpreter.java:163)
	at ij.macro.Interpreter.run(Interpreter.java:93)
	at ij.macro.Interpreter.run(Interpreter.java:107)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:162)
	at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:146)
	at ij.IJ.runMacroFile(IJ.java:171)
	at ij.IJ.runMacroFile(IJ.java:176)
	at Mitochondria_Analyzer.run_Macro(Mitochondria_Analyzer.java:277)
	at Mitochondria_Analyzer.Threshold2D(Mitochondria_Analyzer.java:213)
	at Mitochondria_Analyzer.run(Mitochondria_Analyzer.java:33)
	at ij.IJ.runUserPlugIn(IJ.java:243)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
	
Any ideas on any other things I can try? 

Thank you

**Comment by AhsenChaudhry** [comment]
Hello,
This issue seems to arise when the pixel units are not set properly. Please check the image properties ('Image' -> 'Properties') and ensure that the pixel width, height, and voxel depth are appropriate and that the unit is 'micron' for all three paramaters. Sometimes after certain imaging processing, such as deconvolution, these values are erased and need to be set back to the original values from the raw microscopy data.
